language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install pybuilder
  - pyb install_dependencies

script: "pyb package --debug"

notifications:
  email:
    - arne.hilmann@immobilienscout24.de
    - michael.gruber@immobilienscout24.de
